DROP DATABASE IF EXISTS widget;
CREATE DATABASE widget CHARACTER SET utf8;
USE widget;

DROP TABLE IF EXISTS user;
CREATE TABLE user(
    id INT PRIMARY KEY AUTO_INCREMENT,
    username CHAR(20) NOT NULL UNIQUE,
    password CHAR(64)
);
LOCK TABLES user WRITE;
INSERT INTO `user` VALUES (1,'adm','c0aab8b0d35a6f49d0184695d4f5ce8c');
UNLOCK TABLES;

DROP TABLE IF EXISTS theme;
CREATE TABLE theme(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name CHAR(40) NOT NULL,
    image_url VARCHAR(200),
    zip_url VARCHAR(200)
);
LOCK TABLES user WRITE;
UNLOCK TABLES;
