DROP DATABASE IF EXISTS zero;
CREATE DATABASE zero CHARACTER SET utf8;
USE zero;

DROP TABLE IF EXISTS user;
CREATE TABLE user(
    username CHAR(20) NOT NULL UNIQUE,
    password CHAR(64)
);
LOCK TABLES user WRITE;
UNLOCK TABLES;
